prov/gni: Updated gnix signatures to match direct signatures.
ofi-cray/libfabric-cray pull request #1174
Opened 2017-01-30 18:17 UTC by e-harvey

- Updated eq, cq, ep, atomic, cntr signatures.
- Add dummy gnix_connect for cm.
- _gnix_ep_getinfo now uses ofi_check_domain_attr fn.
- gnix_sep_bind is now a "direct function".

Signed-off-by: Evan Harvey <eharvey@lanl.gov>

2017-01-30 19:11 UTC, jswaro reviewed
Looks fine. How did you test these changes?

2017-01-30 19:18 UTC, e-harvey commented
@jswaro I didn't test these changes (other than compiling) as the functions were simply a copy past of `gnix_cntr_{add,set}` with one minor change -- the counter field. Also, there are no unit tests for `gnix_cntr_{add,set}` in gnitests. I think these changes are simple enough that we should not write unit tests for them. What do you think?

2017-01-30 19:24 UTC, hppritcha commented
It might be useful to try testing against the fabtests built using ./configure CFLAGS="-DFABRIC_DIRECT" blah blah and see if it compiles.

2017-01-30 19:24 UTC, hppritcha commented
I don't think the cray tests use enough of the methods to bring out linking problems associated with incorrect handling of fi_direct within the GNI provider.

2017-01-30 19:38 UTC, jswaro commented
@e-harvey Compile against libfabric direct should be the simple smoke test. There is no point in making these changes if they don't compile. 

It is a bit of a shame that we don't have direct tests yet, but eventually I suppose. 

Please compile this first and report the results.

2017-01-30 19:38 UTC, jswaro requested changes
Check via compile

2017-01-30 20:08 UTC, e-harvey commented
@jswaro: The changes compile and pass gnitest and cray-tests -- I will test fabtests with these changes as well.

2017-01-30 20:25 UTC, e-harvey commented
These changes build against fabtests with no errors or new warnings. I cannot get ccm_runfabtests.sh to run on my side -- perhaps you could test this on your end @jswaro?

2017-01-30 20:36 UTC, jswaro commented
Why does the ccm_runfabtests script fail? Does it give an error message?

2017-01-30 20:38 UTC, e-harvey commented
@jswaro It's due to the machine setup. It hangs at a password prompt.

2017-01-31 00:10 UTC, hppritcha approved these changes

2017-01-31 16:05 UTC, jswaro approved these changes

2017-01-31 16:35 UTC, merged