prov/gni: fix race condition for peer_caps
ofi-cray/libfabric-cray pull request #1239
Opened 2017-03-01 05:15 UTC by hppritcha

testing with Sandia SHMEM(SOS) revealed a problem with setting
peer_caps.  The SOS use of atomics and short puts revealed
a race condition when using FI_PROGRESS_AUTO in setting the peer
caps in the vc structure.

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

2017-03-01 20:24 UTC, chuckfossen requested changes

2017-03-01 20:24 UTC, chuckfossen commented on prov/gni/src/gnix_vc.c
> +		vc->peer_caps = peer_caps;
reminder to move conn_state assignment below peer_caps assignment

2017-03-01 22:04 UTC, hppritcha commented
@chuckfossen modified the peer_caps update as per our conversation this morning.

2017-03-01 23:39 UTC, chuckfossen commented on prov/gni/src/gnix_vc.c
>  	vc->peer_irq_mem_hndl = ep->nic->irq_mem_hndl;
I'm still concerned that conn_state is getting set before we finish filling in the vc struct leading to other issues with fields not filled in when we check for the connected state. I would rather we move the setting of conn_state to the last struct member we fill in here.

2017-03-06 20:48 UTC, hppritcha commented
@chuckfossen check now.

2017-03-06 20:53 UTC, chuckfossen approved these changes

2017-03-06 20:54 UTC, hppritcha commented
okay we'll let travis grind away then merge.

2017-03-06 20:54 UTC, chuckfossen commented
Thanks for changing all the spots that we could be racing.

2017-03-08 18:44 UTC, hppritcha commented
I'm merging this after CI completes.

2017-03-08 21:56 UTC, merged