prov/gni: Keep trying to process work req.
ofi-cray/libfabric-cray pull request #1268
Opened 2017-03-09 19:02 UTC by e-harvey

- Change GNIX_FATAL to GNIX_DEBUG since the
 work req has been enqueued.

The rdm_api/tsend test was reporting a warning due to GNIX_FATAL being called for a recoverable error.

Fixes #1267.

2017-03-09 19:57 UTC, e-harvey commented
@ztiffany Please review when you have time.

2017-03-09 23:25 UTC, sungeunchoi commented
We discussed this in the stand up.  This is not the right fix.  That said, we should keep the formatting and spelling fixes and update the TODO comment on the call to GNIX_FATAL.  Something like, "TODO: somehow return an error to the user (e.g., via a cq error).  This situation can occur if we are try to use a resource that has already been closed.  This will most likely occur at teardown.  We can't do anything about it here, but it should be handled elsewhere."

2017-03-09 23:26 UTC, sungeunchoi requested changes
See my comments.

2017-03-10 01:02 UTC, sungeunchoi commented on prov/gni/src/gnix_vc.c
> +				/* TODO: Report error (via CQ err?) */
Please add that we can't do that at this location in the code.

2017-03-10 01:03 UTC, sungeunchoi commented
Also, title should be updated, and commits squashed with appropriately updated commit message.

2017-03-10 01:40 UTC, sungeunchoi approved these changes

2017-03-10 15:15 UTC, merged