Add domain op to enable trans. CQ IRQs
ofi-cray/libfabric-cray pull request #1292
Opened 2017-03-15 21:48 UTC by ztiffany

Enabling CQ IRQs in GNI allows the data auto progress thread to complete all
transaction asynchronously.

Fixes ofi-cray/libfabric-cray#1036

Signed-off-by: Zach <ztiffany@cray.com>

2017-03-16 15:02 UTC, hppritcha commented
please rebase off of libfabric-cray master to see if LANL-CI is happier now.

2017-03-16 16:03 UTC, hppritcha requested changes
Since you're enabling interrupts on the default tx/rx CQs there's no need to create the second pair of CQs.

I'm also confused how this is suppose to wake up the progress thread.  This PR doesn't change the cq's in the GNI_CQVectorMonitor poll set.

2017-03-24 03:06 UTC, ztiffany commented
I just added a new version of this code.  For "eager auto" mode I only create the 2 blocking CQs and use them for all transactions.  Using this mode does cause a lot of extra contention in the progress loop.  That's leading to doubled latency and a little more than half BW for small message sizes in OSU.  Consider this experimental for now.  For now, enabling this mode was good for finding a race in the progress loop.

gnitest: all passing
SOS: All but global_exit passes.  Many failing tests fixed.
OSU: ran with MPICH.  Most tests passing.  I filed a new bug for a hang in *_acc_latency tests at 16k message size.  That problem exists in master today.

This PR removes a lot of recent code for CM progress.  Reasoning is:
1. sched_new_conn() is called on all newly connected VCs.  It will call push_tx_reqs, so the additional call to push_tx_reqs is redundant.
2. All CM NICs used by an EP that is bound to a CQ or CNTR are added to the CQ/CNTRs poll object list.  We don't need cm_nic_progress directly inside cq/cntr_progress.
3. cm_nic_progress is already called after each time the dgram rcv_cb_fn is run.  It question whether it should be needed anywhere in gnix_vc.c.

2017-03-24 03:07 UTC, ztiffany commented
Setting flags in gnix_msg.c fixes a bug where send/recv interfaces weren't handling FI_FENCE (and maybe other transaction modes) properly.

2017-03-27 22:12 UTC, sungeunchoi commented
This branch fixes the current hangs in the miniapps run that were caused by @hppritcha CM NIC fixes for SOS (#1238).

2017-04-10 19:57 UTC, ztiffany commented
bot:lanl:retest

2017-04-11 17:32 UTC, sungeunchoi commented
Can you add the comment about setting flags to the commit message?

2017-04-12 16:59 UTC, sungeunchoi approved these changes
Other than adding info about bug fix to the commit message, this looks good.

2017-04-12 19:09 UTC, hppritcha approved these changes

2017-04-17 16:06 UTC, merged