prov/gni: swat a bug revealed with SOS testing
ofi-cray/libfabric-cray pull request #1315
Opened 2017-04-04 22:14 UTC by hppritcha

In its usual fashion SOS seems to be really good
at rooting out bugs.  Turns out there are certain
shmem_putmem/quiet call patterns that could cause the GNI provider
to get stuck in an infinite loop, endlessly trying to
progress vc's without ever breaking out to recover more
TXs.

Fixes ofi-cray/libfabric-cray#1314

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

2017-04-05 15:01 UTC, hppritcha commented
hmmm... not sure what's going on with jenkins.

2017-04-06 15:43 UTC, chuckfossen requested changes

2017-04-06 15:43 UTC, chuckfossen commented on prov/gni/src/gnix_vc.c
> +		if (ret_tx != FI_SUCCESS) {
Can you move this debug statement into the if (ret_tx != FI_SUCCESS) below the release of the lock? It would clean it up slightly.

2017-04-06 16:47 UTC, hppritcha commented on prov/gni/src/gnix_vc.c
> +		if (ret_tx != FI_SUCCESS) {
done

2017-04-06 16:48 UTC, chuckfossen approved these changes

2017-04-06 17:58 UTC, hppritcha commented
build failed because of the version problem.  rebasing to clean this up.

2017-04-07 01:14 UTC, merged