prov/gni: add version check to gnix_cq_readerr
ofi-cray/libfabric-cray pull request #1360
Opened 2017-06-06 15:15 UTC by jshimek

If user application provides a buffer and is using
libfabric version 1.5 utilize the buffer, otherwise
fall back to using fabric provided err_buffer.

Update tests so they pass using new capabilities.

fixes ofi-cray/libfabric-cray#1224

Signed-off-by: James Shimek <jshimek@cray.com>

2017-06-06 15:19 UTC, jswaro requested changes
There should be written tests for each of the new conditions introduced in gnix_cq.c. Primarily these new tests should request a different fi_version than the default.

2017-06-06 20:37 UTC, jshimek commented
I've added another test that validates the 1.4 way of doing things for read_cq_err

2017-06-07 16:22 UTC, sungeunchoi commented on prov/gni/test/cq.c
> +void setup_1_4()
This is exactly like the `setup` except the version, right?  Please just pass in the version as an argument to avoid duplication of the code.

2017-06-07 17:02 UTC, jshimek commented on prov/gni/test/cq.c
> +void setup_1_4()
Making the change and pushing up a new commit.

2017-06-07 20:46 UTC, jshimek commented
Does anyone see a problem with the changes that would cause the tests to run long and fail due to timeouts? It seems very odd that this is causing the LANL-CI to fail due to taking to long.

2017-06-08 13:46 UTC, jshimek commented
bot:retest

2017-06-08 16:03 UTC, jswaro approved these changes

2017-06-08 18:42 UTC, chuckfossen approved these changes
update comment

2017-06-08 18:42 UTC, chuckfossen commented on prov/gni/src/gnix_cq.c
>  		 * If buf->err_data_size is zero or the api version is < 1.5,
TODO comment can either be removed or cleaned up.

2017-06-08 18:47 UTC, sungeunchoi commented on prov/gni/src/gnix_cq.c
>  		 * If buf->err_data_size is zero or the api version is < 1.5,
Good point.  Just remove the TODO part, and it should be good.

2017-06-08 18:49 UTC, jshimek commented on prov/gni/src/gnix_cq.c
>  		 * If buf->err_data_size is zero or the api version is < 1.5,
Done.

2017-06-08 18:49 UTC, sungeunchoi approved these changes
Update comment as requested, but then merge away.

2017-06-08 23:01 UTC, jshimek commented
Only change was to add the same special casing to the setup function for mr mode as was done in PR #1372

2017-06-08 23:09 UTC, jshimek commented
bot:retest

2017-06-08 23:42 UTC, merged